import json
import ast
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class KaggleStageDiarizationNotebookTests(unittest.TestCase):
    def test_notebook_runs_one_manual_audio_path_and_prints_results(self):
        notebook = json.loads((ROOT / "kaggle_notebooks" / "07_stage_diarization_only.ipynb").read_text(encoding="utf-8"))
        joined = "\n".join("".join(cell.get("source", [])) for cell in notebook["cells"])

        self.assertIn("AUDIO_INPUT_PATH =", joined)
        self.assertIn('REPO_URL = "https://github.com/tuanad121/sommelier.git"', joined)
        self.assertIn('BRANCH = "kaggle-gpu"', joined)
        self.assertIn("git", joined)
        self.assertIn("clone", joined)
        self.assertIn("TORCH_PACKAGE = \"torch==2.7.1\"", joined)
        self.assertIn("TORCHAUDIO_PACKAGE = \"torchaudio==2.7.1\"", joined)
        self.assertIn("TORCHVISION_PACKAGE = \"torchvision==0.22.1\"", joined)
        self.assertIn('NEMO_PACKAGE = "nemo_toolkit[asr] @ git+https://github.com/NVIDIA/NeMo.git@main"', joined)
        self.assertNotIn("#egg=nemo_toolkit[asr]", joined)
        self.assertIn("PYTORCH_WHEEL_EXTRA_INDEX_URL", joined)
        self.assertIn("requirements-kaggle-diarization.txt", joined)
        self.assertIn("REQUIREMENTS_PATH = PIPELINE_DIR / 'requirements-kaggle-diarization.txt'", joined)
        self.assertIn("str(REQUIREMENTS_PATH)", joined)
        self.assertIn("HF_SECRET_NAME = \"HF_TOKEN\"", joined)
        self.assertIn("UserSecretsClient", joined)
        self.assertIn("huggingface_token", joined)
        self.assertIn('SORTFORMER_MODEL_NAME = "nvidia/diar_streaming_sortformer_4spk-v2.1"', joined)
        self.assertIn("nvidia/diar_streaming_sortformer_4spk-v2.1", joined)
        self.assertIn("pyannote/embedding", joined)
        self.assertIn("SORTFORMER_STREAMING_CONFIG = True", joined)
        self.assertIn("SORTFORMER_CHUNK_LEN = 340", joined)
        self.assertIn("SORTFORMER_CHUNK_LEFT_CONTEXT = 1", joined)
        self.assertIn("SORTFORMER_CHUNK_RIGHT_CONTEXT = 40", joined)
        self.assertIn("SORTFORMER_FIFO_LEN = 40", joined)
        self.assertIn("SORTFORMER_SPKCACHE_UPDATE_PERIOD = 300", joined)
        self.assertIn("SORTFORMER_SPKCACHE_LEN = 200", joined)
        self.assertIn("MIN_SPLIT_SILENCE = 1.0", joined)
        self.assertIn("MAX_DIA_CHUNK_DURATION = 900.0", joined)
        self.assertIn("AUDIO_GAIN_CLAMP_DB = 6.0", joined)
        self.assertIn("print('  audio_gain_clamp_db = +/-', AUDIO_GAIN_CLAMP_DB)", joined)
        self.assertIn("SPEAKER_BOUNDARY_REFINEMENT = True", joined)
        self.assertIn("BOUNDARY_REFINE_MAX_SHIFT = 0.4", joined)
        self.assertIn("BOUNDARY_REFINE_STEP = 0.05", joined)
        self.assertIn("BOUNDARY_REFINE_EMBED_WINDOW = 0.4", joined)
        self.assertIn("BOUNDARY_REFINE_MIN_SEGMENT = 0.6", joined)
        self.assertIn("BOUNDARY_REFINE_MAX_GAP = 0.35", joined)
        self.assertIn("BOUNDARY_REFINE_MIN_IMPROVEMENT = 0.05", joined)
        self.assertIn("Bật/tắt bước tự chỉnh ranh giới giữa 2 speaker", joined)
        self.assertIn("Giới hạn boundary được dịch tối đa", joined)
        self.assertIn("Không để refinement tạo segment quá ngắn", joined)
        self.assertIn("print('  speaker_boundary_refinement =', SPEAKER_BOUNDARY_REFINEMENT)", joined)
        self.assertIn("SORTFORMER_POSTPROCESSING = True", joined)
        self.assertIn("SORTFORMER_POSTPROCESSING_YAML = OUTPUT_ROOT / 'sortformer_postprocessing.yaml'", joined)
        self.assertIn("SORTFORMER_PP_ONSET = 0.3", joined)
        self.assertIn("SORTFORMER_PP_OFFSET = 0.33", joined)
        self.assertIn("SORTFORMER_PP_PAD_ONSET = 0.015", joined)
        self.assertIn("SORTFORMER_PP_PAD_OFFSET = 0.015", joined)
        self.assertIn("SORTFORMER_PP_MIN_DURATION_ON = 0.35", joined)
        self.assertIn("SORTFORMER_PP_MIN_DURATION_OFF = 0.35", joined)
        self.assertIn("SORTFORMER_BATCH_SIZE = 1", joined)
        self.assertIn("SORTFORMER_NUM_WORKERS = 0", joined)
        self.assertIn("sortformer_pp = {", joined)
        self.assertIn("'parameters': sortformer_pp", joined)
        self.assertIn("--sortformer-postprocessing", joined)
        self.assertIn("--sortformer-postprocessing-yaml", joined)
        self.assertIn("--sortformer-pp-onset", joined)
        self.assertIn("--sortformer-pp-offset", joined)
        self.assertIn("--sortformer-pp-pad-onset", joined)
        self.assertIn("--sortformer-pp-pad-offset", joined)
        self.assertIn("--sortformer-pp-min-duration-on", joined)
        self.assertIn("--sortformer-pp-min-duration-off", joined)
        self.assertIn("--sortformer_batch_size", joined)
        self.assertIn("--sortformer_num_workers", joined)
        self.assertIn("--sortformer_model_name", joined)
        self.assertIn("--sortformer-streaming-config", joined)
        self.assertIn("--sortformer_chunk_len", joined)
        self.assertIn("--sortformer_chunk_left_context", joined)
        self.assertIn("--sortformer_chunk_right_context", joined)
        self.assertIn("--sortformer_fifo_len", joined)
        self.assertIn("--sortformer_spkcache_update_period", joined)
        self.assertIn("--sortformer_spkcache_len", joined)
        self.assertIn("--min_split_silence", joined)
        self.assertIn("--max_dia_chunk_duration", joined)
        self.assertIn("--audio-gain-clamp-db", joined)
        self.assertIn("str(AUDIO_GAIN_CLAMP_DB)", joined)
        self.assertIn("--speaker-boundary-refinement", joined)
        self.assertIn("--boundary-refine-max-shift", joined)
        self.assertIn("--boundary-refine-step", joined)
        self.assertIn("--boundary-refine-embed-window", joined)
        self.assertIn("--boundary-refine-min-segment", joined)
        self.assertIn("--boundary-refine-max-gap", joined)
        self.assertIn("--boundary-refine-min-improvement", joined)
        self.assertIn("--input_audio_path", joined)
        self.assertNotIn("--input_folder_path", joined)
        self.assertIn("diarization.json", joined)
        self.assertIn("pd.DataFrame", joined)
        self.assertIn("display(", joined)
        self.assertIn("speaker_summary", joined)
        self.assertIn("IPython.display", joined)
        self.assertIn("Audio(", joined)
        self.assertIn("FULL_AUDIO_PATH = RUN_DIR / '00_input' / 'full.wav'", joined)
        self.assertIn("SEGMENT_AUDIO_DIR = RUN_DIR / '01_diarization' / 'segment_audio_preview'", joined)
        self.assertIn("full_audio = Audio(str(FULL_AUDIO_PATH))", joined)
        self.assertIn("segment_audio", joined)
        self.assertIn("display(segment_audio_df", joined)
        self.assertNotIn("build_trace_html.py", joined)
        self.assertNotIn("compare_diarization_run_to_golden.py", joined)

        for idx, cell in enumerate(notebook["cells"]):
            if cell.get("cell_type") != "code":
                continue
            source = "".join(cell.get("source", []))
            ast.parse(source, filename=f"07_stage_diarization_only.ipynb:cell{idx}")

    def test_stage_diarization_notebook_builder_tracks_update_source(self):
        builder = (ROOT / "tools" / "build_kaggle_stage_diarization_notebook.py").read_text(encoding="utf-8")

        self.assertIn('SOURCE_PATH = Path("kaggle_notebooks/stage1_updated.ipynb")', builder)
        self.assertIn('OUT_PATH = Path("kaggle_notebooks/07_stage_diarization_only.ipynb")', builder)
        self.assertIn('"AUDIO_GAIN_CLAMP_DB"', builder)
        self.assertIn('"AUDIO_GAIN_CLAMP_DB": "6.0"', builder)
        self.assertIn('"SPEAKER_BOUNDARY_REFINEMENT"', builder)
        self.assertIn('"SPEAKER_BOUNDARY_REFINEMENT": "True"', builder)
        self.assertIn('"BOUNDARY_REFINE_MAX_SHIFT": "0.4"', builder)
        self.assertIn('"BOUNDARY_REFINE_STEP": "0.05"', builder)
        self.assertIn('"BOUNDARY_REFINE_EMBED_WINDOW": "0.4"', builder)
        self.assertIn('"BOUNDARY_REFINE_MIN_SEGMENT": "0.6"', builder)
        self.assertIn('"BOUNDARY_REFINE_MAX_GAP": "0.35"', builder)
        self.assertIn('"BOUNDARY_REFINE_MIN_IMPROVEMENT": "0.05"', builder)
        self.assertIn('"SORTFORMER_SPKCACHE_LEN": "200"', builder)
        self.assertIn('"SORTFORMER_PP_ONSET": "0.3"', builder)
        self.assertIn('"SORTFORMER_PP_OFFSET": "0.33"', builder)
        self.assertIn('"SORTFORMER_PP_PAD_ONSET": "0.015"', builder)
        self.assertIn('"SORTFORMER_PP_PAD_OFFSET": "0.015"', builder)
        self.assertIn('"SORTFORMER_PP_MIN_DURATION_ON": "0.35"', builder)
        self.assertIn('"SORTFORMER_PP_MIN_DURATION_OFF": "0.35"', builder)


if __name__ == "__main__":
    unittest.main()
