import ast
import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = ROOT / "kaggle_notebooks" / "08_stage_music_overlap_only.ipynb"
GENERATOR_PATH = ROOT / "tools" / "build_kaggle_stage_music_overlap_notebook.py"


class KaggleStageMusicOverlapNotebookTests(unittest.TestCase):
    def test_notebook_runs_only_stage_02_and_03_from_stage_01_artifacts(self):
        notebook = json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))
        joined = "\n".join("".join(cell.get("source", [])) for cell in notebook["cells"])

        self.assertIn('REPO_URL = "https://github.com/tuanad121/sommelier.git"', joined)
        self.assertIn('BRANCH = "kaggle-gpu"', joined)
        self.assertIn("DIARIZATION_JSON_PATH =", joined)
        self.assertIn("AUDIO_WAV_PATH =", joined)
        self.assertIn("OUTPUT_RUN_DIR =", joined)
        self.assertIn("DIARIZATION_JSON =", joined)
        self.assertIn("FULL_AUDIO_PATH =", joined)
        self.assertIn("def safe_stem(path):", joined)
        self.assertIn("def is_writable_stage1_run_dir", joined)
        self.assertIn('str(candidate).startswith("/kaggle/input")', joined)
        self.assertIn('RUN_DIR = OUTPUT_ROOT / f"stage23_{safe_stem(FULL_AUDIO_PATH)}"', joined)
        self.assertIn("RUN_DEMUCS = True", joined)
        self.assertIn("RUN_METIS_TSE = True", joined)
        self.assertIn("OVERLAP_THRESHOLD = 1.0", joined)
        self.assertIn('METIS_REPO_URL = "https://github.com/open-mmlab/Amphion.git"', joined)
        self.assertIn('METIS_REPO_DIR = Path("/kaggle/working/Amphion")', joined)
        self.assertIn("METIS_CKPT_DIR =", joined)
        self.assertIn("METIS_N_TIMESTEPS = 10", joined)
        self.assertIn("def required_metis_paths", joined)
        self.assertIn("def missing_metis_paths", joined)
        self.assertIn("def is_valid_metis_repo", joined)
        self.assertIn('METIS_REPO_DIR / "models/tts/metis/metis.py"', joined)
        self.assertIn('"models/tts/metis/config/tse.json"', joined)
        self.assertIn('"models/tts/maskgct/maskgct_utils.py"', joined)
        self.assertIn("Missing Metis repo files", joined)
        self.assertIn("not is_valid_metis_repo(METIS_REPO_DIR)", joined)
        self.assertIn('SETUPTOOLS_PACKAGE = "setuptools>=70.0.0"', joined)
        self.assertIn('PANNS_PACKAGE = "panns-inference"', joined)
        self.assertIn('PILLOW_PACKAGE = "pillow==11.3.0"', joined)
        self.assertIn('TRANSFORMERS_PACKAGE = "transformers==4.51.3"', joined)
        self.assertIn('TOKENIZERS_PACKAGE = "tokenizers>=0.21,<0.22"', joined)
        self.assertIn('PEFT_PACKAGE = "peft==0.16.0"', joined)
        self.assertIn('NUMPY_PACKAGE = "numpy==1.26.4"', joined)
        self.assertIn('"librosa==0.10.2.post1"', joined)
        self.assertIn('"soundfile==0.12.1"', joined)
        self.assertIn("TRANSFORMERS_PACKAGE,", joined)
        self.assertIn("TOKENIZERS_PACKAGE,", joined)
        self.assertIn('"accelerate==1.9.0"', joined)
        self.assertIn('"safetensors"', joined)
        self.assertIn("PEFT_PACKAGE,", joined)
        self.assertIn("from accelerate.utils.memory import clear_device_cache", joined)
        self.assertIn("accelerate clear_device_cache import OK", joined)
        self.assertIn("def clear_import_prefixes", joined)
        self.assertIn("def install_python_packages", joined)
        self.assertIn("def ensure_peft_stack", joined)
        self.assertIn("from transformers import EncoderDecoderCache", joined)
        self.assertIn("transformers EncoderDecoderCache import OK", joined)
        self.assertIn('install_python_packages([TRANSFORMERS_PACKAGE, TOKENIZERS_PACKAGE, PEFT_PACKAGE]', joined)
        self.assertIn('"13_pip_transformers_peft_runtime.log"', joined)
        self.assertIn("peft import OK", joined)
        self.assertIn('"langid"', joined)
        self.assertIn('"pyopenjtalk"', joined)
        self.assertIn("amphion/metis", joined)
        self.assertIn("amphion/MaskGCT", joined)
        self.assertIn('"espeak-ng"', joined)
        self.assertIn('"libespeak-ng1"', joined)
        self.assertIn("from phonemizer.backend import EspeakBackend", joined)
        self.assertIn("EspeakBackend.is_available()", joined)
        self.assertIn("espeak-ng available for phonemizer", joined)
        self.assertIn("import sys", joined)
        self.assertIn('run_logged([sys.executable, "-m", "pip", "uninstall", "-y", "Pillow", "pillow"]', joined)
        self.assertIn('run_logged([sys.executable, "-m", "pip", "install", "--no-cache-dir", "--force-reinstall", PILLOW_PACKAGE]', joined)
        self.assertNotIn('["python", "-m", "pip"', joined)
        self.assertIn("from PIL import Image, ImageDraw, ImageFont", joined)
        self.assertIn("Pillow image modules import OK", joined)
        self.assertNotIn("from PIL import ImageText", joined)
        self.assertNotIn("from PIL._typing import _Ink", joined)
        self.assertNotIn("librosa==0.11.0", joined)
        self.assertNotIn("soundfile==0.13.1", joined)
        self.assertNotIn("numpy==2.2.6", joined)
        self.assertNotIn("transformers==4.41.2", joined)
        self.assertIn("PANNS_DEVICE_INDEX = 0", joined)
        self.assertIn("DEMUCS_DEVICE_INDEX = 0", joined)
        self.assertIn("METIS_DEVICE_INDEX = 0", joined)
        self.assertNotIn('"clearvoice==0.1.2"', joined)
        self.assertNotIn('"modelscope"', joined)
        self.assertNotIn('"pyannote.audio==3.3.2"', joined)
        self.assertNotIn('"pyannote.audio",', joined)
        self.assertNotIn('"lightning==2.4.0"', joined)
        self.assertNotIn('"pytorch-lightning==2.5.2"', joined)
        self.assertIn("hf_hub_download", joined)
        self.assertIn("snapshot_download", joined)
        self.assertIn('run_logged([sys.executable, "-m", "pip", "install", "--no-cache-dir", "--force-reinstall", "--no-deps", PANNS_PACKAGE]', joined)
        self.assertIn("def ensure_python_module", joined)
        self.assertIn("except ModuleNotFoundError as exc", joined)
        self.assertIn("if exc.name != module_name", joined)
        self.assertIn("importlib.invalidate_caches()", joined)
        self.assertIn('ensure_python_module("panns_inference", PANNS_PACKAGE, "12_pip_panns_inference_runtime.log", install_args=["--no-deps"])', joined)
        self.assertIn("panns_inference import OK", joined)
        self.assertIn("run_stage_music_overlap_only.py", joined)
        self.assertIn("cmd = [\n    sys.executable, str(PIPELINE_DIR / \"run_stage_music_overlap_only.py\")", joined)
        self.assertNotIn("cmd = [\n    \"python\"", joined)
        self.assertIn("--audio_path", joined)
        self.assertIn("--diarization_json", joined)
        self.assertIn("--output_run_dir", joined)
        self.assertIn("--overlap_threshold", joined)
        self.assertIn("--demucs", joined)
        self.assertIn("--metis_tse", joined)
        self.assertIn("--metis_device_index", joined)
        self.assertIn("--metis_repo_dir", joined)
        self.assertIn("--metis_ckpt_dir", joined)
        self.assertNotIn("--clearvoice_tse", joined)
        self.assertNotIn("--clearvoice_device_index", joined)
        self.assertNotIn("--sepreformer", joined)
        self.assertNotIn("SEPREFORMER", joined)
        self.assertNotIn("SepReformer", joined)
        self.assertIn("02_music_clean/segment_flags.json", joined)
        self.assertIn("03_overlap/segments.json", joined)
        self.assertIn("cleaned_audio = Audio(", joined)
        self.assertIn("segment_audio_df", joined)
        self.assertNotIn("run_stage_diarization_only.py", joined)
        self.assertNotIn("main_original_ASR_MoE.py", joined)
        self.assertNotIn("build_trace_html.py", joined)
        self.assertNotIn("compare_diarization_run_to_golden.py", joined)

        for idx, cell in enumerate(notebook["cells"]):
            if cell.get("cell_type") != "code":
                continue
            source = "".join(cell.get("source", []))
            ast.parse(source, filename=f"08_stage_music_overlap_only.ipynb:cell{idx}")

    def test_generator_builds_stage_music_overlap_notebook(self):
        generator = GENERATOR_PATH.read_text(encoding="utf-8")

        self.assertIn('OUT_PATH = Path("kaggle_notebooks/08_stage_music_overlap_only.ipynb")', generator)
        self.assertIn("run_stage_music_overlap_only.py", generator)
        self.assertIn("DIARIZATION_JSON_PATH", generator)
        self.assertIn("OUTPUT_RUN_DIR", generator)
        self.assertIn("is_writable_stage1_run_dir", generator)
        self.assertIn('str(candidate).startswith("/kaggle/input")', generator)
        self.assertIn("RUN_METIS_TSE", generator)
        self.assertIn("METIS_REPO_URL", generator)
        self.assertIn("METIS_REPO_DIR", generator)
        self.assertIn("def required_metis_paths", generator)
        self.assertIn("def missing_metis_paths", generator)
        self.assertIn("def is_valid_metis_repo", generator)
        self.assertIn('METIS_REPO_DIR / "models/tts/metis/metis.py"', generator)
        self.assertIn('"models/tts/metis/config/tse.json"', generator)
        self.assertIn('"models/tts/maskgct/maskgct_utils.py"', generator)
        self.assertIn("Missing Metis repo files", generator)
        self.assertIn("not is_valid_metis_repo(METIS_REPO_DIR)", generator)
        self.assertIn('SETUPTOOLS_PACKAGE = "setuptools>=70.0.0"', generator)
        self.assertIn('PANNS_PACKAGE = "panns-inference"', generator)
        self.assertIn('PILLOW_PACKAGE = "pillow==11.3.0"', generator)
        self.assertIn('TRANSFORMERS_PACKAGE = "transformers==4.51.3"', generator)
        self.assertIn('TOKENIZERS_PACKAGE = "tokenizers>=0.21,<0.22"', generator)
        self.assertIn('PEFT_PACKAGE = "peft==0.16.0"', generator)
        self.assertIn('"librosa==0.10.2.post1"', generator)
        self.assertIn('"soundfile==0.12.1"', generator)
        self.assertIn("TRANSFORMERS_PACKAGE,", generator)
        self.assertIn("TOKENIZERS_PACKAGE,", generator)
        self.assertIn('"accelerate==1.9.0"', generator)
        self.assertIn('"safetensors"', generator)
        self.assertIn("PEFT_PACKAGE,", generator)
        self.assertIn("from accelerate.utils.memory import clear_device_cache", generator)
        self.assertIn("accelerate clear_device_cache import OK", generator)
        self.assertIn("def clear_import_prefixes", generator)
        self.assertIn("def install_python_packages", generator)
        self.assertIn("def ensure_peft_stack", generator)
        self.assertIn("from transformers import EncoderDecoderCache", generator)
        self.assertIn("transformers EncoderDecoderCache import OK", generator)
        self.assertIn('install_python_packages([TRANSFORMERS_PACKAGE, TOKENIZERS_PACKAGE, PEFT_PACKAGE]', generator)
        self.assertIn('"13_pip_transformers_peft_runtime.log"', generator)
        self.assertIn("peft import OK", generator)
        self.assertIn("amphion/metis", generator)
        self.assertIn("amphion/MaskGCT", generator)
        self.assertIn('"espeak-ng"', generator)
        self.assertIn('"libespeak-ng1"', generator)
        self.assertIn("from phonemizer.backend import EspeakBackend", generator)
        self.assertIn("EspeakBackend.is_available()", generator)
        self.assertIn("import sys", generator)
        self.assertIn('run_logged([sys.executable, "-m", "pip", "uninstall", "-y", "Pillow", "pillow"]', generator)
        self.assertIn('run_logged([sys.executable, "-m", "pip", "install", "--no-cache-dir", "--force-reinstall", PILLOW_PACKAGE]', generator)
        self.assertNotIn('["python", "-m", "pip"', generator)
        self.assertIn("from PIL import Image, ImageDraw, ImageFont", generator)
        self.assertIn("Pillow image modules import OK", generator)
        self.assertNotIn("from PIL import ImageText", generator)
        self.assertNotIn("from PIL._typing import _Ink", generator)
        self.assertIn("def ensure_python_module", generator)
        self.assertIn("except ModuleNotFoundError as exc", generator)
        self.assertIn("if exc.name != module_name", generator)
        self.assertIn("importlib.invalidate_caches()", generator)
        self.assertIn('ensure_python_module("panns_inference", PANNS_PACKAGE, "12_pip_panns_inference_runtime.log", install_args=["--no-deps"])', generator)
        self.assertIn("panns_inference import OK", generator)
        self.assertNotIn('"clearvoice==0.1.2"', generator)
        self.assertNotIn('"modelscope"', generator)
        self.assertIn('NUMPY_PACKAGE = "numpy==1.26.4"', generator)
        self.assertNotIn("librosa==0.11.0", generator)
        self.assertNotIn("numpy==2.2.6", generator)
        self.assertNotIn("transformers==4.41.2", generator)
        self.assertNotIn('"pyannote.audio==3.3.2"', generator)
        self.assertNotIn('"pyannote.audio",', generator)
        self.assertNotIn('"lightning==2.4.0"', generator)
        self.assertIn("--metis_tse", generator)
        self.assertIn('sys.executable, str(PIPELINE_DIR / "run_stage_music_overlap_only.py")', generator)
        self.assertNotIn('"python", str(PIPELINE_DIR / "run_stage_music_overlap_only.py")', generator)
        self.assertIn("--metis_repo_dir", generator)
        self.assertNotIn("--clearvoice_tse", generator)
        self.assertNotIn("--sepreformer", generator)


if __name__ == "__main__":
    unittest.main()
